- name: Enable to install PHP 7.4
  shell:
    cmd: "amazon-linux-extras enable php7.4"
  changed_when: False

- name: Install php and php's modules
  yum:
    name:
      - php
      - php-mbstring
      - php-xml
      - php-mysqlnd
    state: latest
