- name: Download wordpress
  get_url:
    url: https://ja.wordpress.org/wordpress-6.0.1-ja.tar.gz
    dest: /tmp/

- name: Unarcive wordpress
  unarchive:
    src: /tmp/wordpress-6.0.1-ja.tar.gz
    dest: /tmp/
    remote_src: yes

- name: Copy wordpress files to /var/www/html/
  copy:
    src: /tmp/wordpress/
    dest: /var/www/html/
    remote_src: yes
    owner: apache
    group: apache
