- name: Install the latest version of Apache
  yum:
    name: httpd
    state: latest

- name: Install MySQL
  yum:
    name: mysql
    state: latest

- name: Enable service httpd
  systemd:
    name: httpd
    state: started
    enabled: yes
